/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AllReactionsViewModel
 */
export interface AllReactionsViewModel {
    /**
     * 
     * @type {number}
     * @memberof AllReactionsViewModel
     */
    likeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AllReactionsViewModel
     */
    dislikeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AllReactionsViewModel
     */
    viewCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AllReactionsViewModel
     */
    celebrateCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AllReactionsViewModel
     */
    coolCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AllReactionsViewModel
     */
    handsUpCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AllReactionsViewModel
     */
    doesCurrentUserLike?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AllReactionsViewModel
     */
    doesCurrentUserDislike?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AllReactionsViewModel
     */
    doesCurrentUserCelebrate?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AllReactionsViewModel
     */
    doesCurrentUserCool?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AllReactionsViewModel
     */
    doesCurrentUserHandsUp?: boolean;
}
