/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AssetPackAttributes
 */
export interface AssetPackAttributes {
    /**
     * 
     * @type {number}
     * @memberof AssetPackAttributes
     */
    commonCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AssetPackAttributes
     */
    uncommonCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AssetPackAttributes
     */
    rareCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AssetPackAttributes
     */
    epicCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AssetPackAttributes
     */
    legendaryCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AssetPackAttributes
     */
    grailCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AssetPackAttributes
     */
    otherCount?: number;
}
