/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Bid
 */
export interface Bid {
    /**
     * 
     * @type {string}
     * @memberof Bid
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Bid
     */
    isDeleted?: any;
    /**
     * 
     * @type {Date}
     * @memberof Bid
     */
    created?: any;
    /**
     * 
     * @type {Date}
     * @memberof Bid
     */
    updated?: any;
    /**
     * 
     * @type {string}
     * @memberof Bid
     */
    livestreamId?: any;
    /**
     * 
     * @type {string}
     * @memberof Bid
     */
    assetId?: any;
}
