/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BarcodeType } from './barcode-type';
import { CollectibleType } from './collectible-type';
/**
 * 
 * @export
 * @interface Collectible
 */
export interface Collectible {
    /**
     * 
     * @type {string}
     * @memberof Collectible
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Collectible
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Collectible
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Collectible
     */
    updated?: Date;
    /**
     * 
     * @type {string}
     * @memberof Collectible
     */
    collectibleSeriesId?: string;
    /**
     * 
     * @type {string}
     * @memberof Collectible
     */
    collectibleBrandId?: string;
    /**
     * 
     * @type {string}
     * @memberof Collectible
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Collectible
     */
    year?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Collectible
     */
    issueNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Collectible
     */
    volume?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Collectible
     */
    barcode?: string | null;
    /**
     * 
     * @type {BarcodeType}
     * @memberof Collectible
     */
    barcodeType?: BarcodeType;
    /**
     * 
     * @type {CollectibleType}
     * @memberof Collectible
     */
    collectibleType?: CollectibleType;
}
