/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserCollectibleAttributes } from './user-collectible-attributes';
/**
 * 
 * @export
 * @interface CollectibleViewModel
 */
export interface CollectibleViewModel {
    /**
     * 
     * @type {string}
     * @memberof CollectibleViewModel
     */
    userCollectibleId?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectibleViewModel
     */
    collectibleId?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectibleViewModel
     */
    collectibleBrandId?: string;
    /**
     * 
     * @type {string}
     * @memberof CollectibleViewModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectibleViewModel
     */
    year?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectibleViewModel
     */
    issueNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectibleViewModel
     */
    volume?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectibleViewModel
     */
    attributes?: string | null;
    /**
     * 
     * @type {UserCollectibleAttributes}
     * @memberof CollectibleViewModel
     */
    userCollectibleAttributes?: UserCollectibleAttributes;
}
