/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssetPackAttributes } from './asset-pack-attributes';
import { AssetPackType } from './asset-pack-type';
/**
 * 
 * @export
 * @interface CreateAssetPackRequestModel
 */
export interface CreateAssetPackRequestModel {
    /**
     * 
     * @type {string}
     * @memberof CreateAssetPackRequestModel
     */
    name?: string | null;
    /**
     * 
     * @type {AssetPackType}
     * @memberof CreateAssetPackRequestModel
     */
    assetPackType?: AssetPackType;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAssetPackRequestModel
     */
    walletAssetIds?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateAssetPackRequestModel
     */
    randomizePacks?: boolean;
    /**
     * 
     * @type {AssetPackAttributes}
     * @memberof CreateAssetPackRequestModel
     */
    assetPackAttributes?: AssetPackAttributes;
}
