/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CustomerPaymentMethod
 */
export interface CustomerPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof CustomerPaymentMethod
     */
    paymentMethodId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPaymentMethod
     */
    customerId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerPaymentMethod
     */
    customerName?: any | null;
    /**
     * 
     * @type {CustomerCard}
     * @memberof CustomerPaymentMethod
     */
    card?: any;
}
