/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CustomerCard
 */
export interface CustomerCard {
    /**
     * 
     * @type {string}
     * @memberof CustomerCard
     */
    customerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerCard
     */
    customerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerCard
     */
    cardId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerCard
     */
    last4?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CustomerCard
     */
    expMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomerCard
     */
    expYear?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CustomerCard
     */
    isDefault?: boolean;
}
