/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DirectSaleWithAssets
 */
export interface DirectSaleWithAssets {
    /**
     * 
     * @type {DirectSale}
     * @memberof DirectSaleWithAssets
     */
    sale?: any;
    /**
     * 
     * @type {Array&lt;SaleAsset&gt;}
     * @memberof DirectSaleWithAssets
     */
    saleAssets?: any | null;
}
