/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface DirectSale
 */
export interface DirectSale {
    /**
     * 
     * @type {string}
     * @memberof DirectSale
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof DirectSale
     */
    isDeleted?: any;
    /**
     * 
     * @type {Date}
     * @memberof DirectSale
     */
    created?: any;
    /**
     * 
     * @type {Date}
     * @memberof DirectSale
     */
    updated?: any;
    /**
     * 
     * @type {string}
     * @memberof DirectSale
     */
    livestreamId?: any | null;
    /**
     * 
     * @type {SaleType}
     * @memberof DirectSale
     */
    saleType?: any;
    /**
     * 
     * @type {SaleStatus}
     * @memberof DirectSale
     */
    saleStatus?: any;
    /**
     * 
     * @type {number}
     * @memberof DirectSale
     */
    floorPrice?: any;
    /**
     * 
     * @type {Date}
     * @memberof DirectSale
     */
    startTime?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof DirectSale
     */
    endTime?: any | null;
    /**
     * 
     * @type {string}
     * @memberof DirectSale
     */
    winningBuyOrderId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof DirectSale
     */
    name?: any | null;
    /**
     * 
     * @type {string}
     * @memberof DirectSale
     */
    description?: any | null;
    /**
     * 
     * @type {DirectSaleStatus}
     * @memberof DirectSale
     */
    status?: any;
    /**
     * 
     * @type {string}
     * @memberof DirectSale
     */
    sellerVideoUrl?: any | null;
}
