/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FileEncodingType } from './file-encoding-type';
import { FileRequestType } from './file-request-type';
/**
 * 
 * @export
 * @interface FileUploadRequest
 */
export interface FileUploadRequest {
    /**
     * 
     * @type {string}
     * @memberof FileUploadRequest
     */
    fileName?: string | null;
    /**
     * 
     * @type {FileEncodingType}
     * @memberof FileUploadRequest
     */
    fileEncodingType?: FileEncodingType;
    /**
     * 
     * @type {FileRequestType}
     * @memberof FileUploadRequest
     */
    fileRequestType?: FileRequestType;
}
