/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum FileRequestType {
    User = 'User',
    UserCover = 'UserCover',
    Livestream = 'Livestream',
    IPFS = 'IPFS',
    ImagePost = 'ImagePost',
    VideoPost = 'VideoPost',
    PhysicalAssetImage = 'PhysicalAssetImage',
    PhysicalAssetVideo = 'PhysicalAssetVideo',
    Vids = 'Vids',
    VidCover = 'VidCover',
    Collectible = 'Collectible',
    Category = 'Category'
}

