/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GiveawayType } from './giveaway-type';
/**
 * 
 * @export
 * @interface Giveaway
 */
export interface Giveaway {
    /**
     * 
     * @type {string}
     * @memberof Giveaway
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Giveaway
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Giveaway
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Giveaway
     */
    updated?: Date;
    /**
     * 
     * @type {string}
     * @memberof Giveaway
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Giveaway
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Giveaway
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Giveaway
     */
    endTime?: Date;
    /**
     * 
     * @type {GiveawayType}
     * @memberof Giveaway
     */
    giveawayType?: GiveawayType;
    /**
     * 
     * @type {string}
     * @memberof Giveaway
     */
    giveawayParentId?: string;
}
