/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IExtendedTweet
 */
export interface IExtendedTweet {
    /**
     * 
     * @type {string}
     * @memberof IExtendedTweet
     */
    text?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IExtendedTweet
     */
    fullText?: any | null;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof IExtendedTweet
     */
    displayTextRange?: any | null;
    /**
     * 
     * @type {ITweetEntities}
     * @memberof IExtendedTweet
     */
    legacyEntities?: any;
    /**
     * 
     * @type {ITweetEntities}
     * @memberof IExtendedTweet
     */
    extendedEntities?: any;
}
