/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IMediaEntitySize
 */
export interface IMediaEntitySize {
    /**
     * 
     * @type {number}
     * @memberof IMediaEntitySize
     */
    width?: any | null;
    /**
     * 
     * @type {number}
     * @memberof IMediaEntitySize
     */
    height?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IMediaEntitySize
     */
    resize?: any | null;
}
