/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IMediaEntity
 */
export interface IMediaEntity {
    /**
     * 
     * @type {number}
     * @memberof IMediaEntity
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IMediaEntity
     */
    idStr?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IMediaEntity
     */
    mediaURL?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IMediaEntity
     */
    mediaURLHttps?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IMediaEntity
     */
    url?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IMediaEntity
     */
    displayURL?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IMediaEntity
     */
    expandedURL?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IMediaEntity
     */
    mediaType?: any | null;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof IMediaEntity
     */
    indices?: any | null;
    /**
     * 
     * @type {{ [key, string]: IMediaEntitySize;}}
     * @memberof IMediaEntity
     */
    sizes?: any | null;
    /**
     * 
     * @type {IVideoInformationEntity}
     * @memberof IMediaEntity
     */
    videoDetails?: any;
}
