/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IPlace
 */
export interface IPlace {
    /**
     * 
     * @type {string}
     * @memberof IPlace
     */
    idStr?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IPlace
     */
    name?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IPlace
     */
    fullName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IPlace
     */
    url?: any | null;
    /**
     * 
     * @type {PlaceType}
     * @memberof IPlace
     */
    placeType?: any;
    /**
     * 
     * @type {string}
     * @memberof IPlace
     */
    country?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IPlace
     */
    countryCode?: any | null;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof IPlace
     */
    attributes?: any | null;
    /**
     * 
     * @type {Array&lt;IPlace&gt;}
     * @memberof IPlace
     */
    containedWithin?: any | null;
    /**
     * 
     * @type {IGeo}
     * @memberof IPlace
     */
    boundingBox?: any;
    /**
     * 
     * @type {IGeo}
     * @memberof IPlace
     */
    geometry?: any;
}
