/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ITweetEntities
 */
export interface ITweetEntities {
    /**
     * 
     * @type {Array&lt;IUrlEntity&gt;}
     * @memberof ITweetEntities
     */
    urls?: any | null;
    /**
     * 
     * @type {Array&lt;IUserMentionEntity&gt;}
     * @memberof ITweetEntities
     */
    userMentions?: any | null;
    /**
     * 
     * @type {Array&lt;IHashtagEntity&gt;}
     * @memberof ITweetEntities
     */
    hashtags?: any | null;
    /**
     * 
     * @type {Array&lt;ISymbolEntity&gt;}
     * @memberof ITweetEntities
     */
    symbols?: any | null;
    /**
     * 
     * @type {Array&lt;IMediaEntity&gt;}
     * @memberof ITweetEntities
     */
    medias?: any | null;
}
