/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ITweetIdentifier
 */
export interface ITweetIdentifier {
    /**
     * 
     * @type {number}
     * @memberof ITweetIdentifier
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof ITweetIdentifier
     */
    idStr?: any | null;
}
