/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IUrlEntity
 */
export interface IUrlEntity {
    /**
     * 
     * @type {string}
     * @memberof IUrlEntity
     */
    url?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IUrlEntity
     */
    displayedURL?: any | null;
    /**
     * 
     * @type {string}
     * @memberof IUrlEntity
     */
    expandedURL?: any | null;
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof IUrlEntity
     */
    indices?: any | null;
}
