/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IVideoInformationEntity
 */
export interface IVideoInformationEntity {
    /**
     * 
     * @type {Array&lt;number&gt;}
     * @memberof IVideoInformationEntity
     */
    aspectRatio?: any | null;
    /**
     * 
     * @type {number}
     * @memberof IVideoInformationEntity
     */
    durationInMilliseconds?: any;
    /**
     * 
     * @type {Array&lt;IVideoEntityVariant&gt;}
     * @memberof IVideoInformationEntity
     */
    variants?: any | null;
}
