/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SaleAssetType } from './sale-asset-type';
import { SaleAssetWithMetadata } from './sale-asset-with-metadata';
import { SaleStatus } from './sale-status';
import { SaleType } from './sale-type';
/**
 * 
 * @export
 * @interface MarketplaceSale
 */
export interface MarketplaceSale {
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarketplaceSale
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof MarketplaceSale
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MarketplaceSale
     */
    updated?: Date;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    livestreamId?: string | null;
    /**
     * 
     * @type {SaleType}
     * @memberof MarketplaceSale
     */
    saleType?: SaleType;
    /**
     * 
     * @type {SaleStatus}
     * @memberof MarketplaceSale
     */
    saleStatus?: SaleStatus;
    /**
     * 
     * @type {SaleAssetType}
     * @memberof MarketplaceSale
     */
    saleAssetType?: SaleAssetType;
    /**
     * 
     * @type {number}
     * @memberof MarketplaceSale
     */
    floorPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof MarketplaceSale
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    saleParentId?: string;
    /**
     * 
     * @type {Date}
     * @memberof MarketplaceSale
     */
    startTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof MarketplaceSale
     */
    endTime?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    winningBuyOrderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    sellerUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    categoryId?: string;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    communityId?: string;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    assetPackId?: string;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    assetId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarketplaceSale
     */
    isListedOnMarketplace?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MarketplaceSale
     */
    isSellerPaid?: boolean;
    /**
     * 
     * @type {Array<SaleAssetWithMetadata>}
     * @memberof MarketplaceSale
     */
    saleAssets?: Array<SaleAssetWithMetadata> | null;
    /**
     * 
     * @type {string}
     * @memberof MarketplaceSale
     */
    sellerName?: string | null;
}
