/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OrderFulfillment
 */
export interface OrderFulfillment {
    /**
     * 
     * @type {string}
     * @memberof OrderFulfillment
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof OrderFulfillment
     */
    isDeleted?: any;
    /**
     * 
     * @type {Date}
     * @memberof OrderFulfillment
     */
    created?: any;
    /**
     * 
     * @type {Date}
     * @memberof OrderFulfillment
     */
    updated?: any;
    /**
     * 
     * @type {string}
     * @memberof OrderFulfillment
     */
    saleId?: any;
    /**
     * 
     * @type {string}
     * @memberof OrderFulfillment
     */
    buyOrderId?: any;
    /**
     * 
     * @type {string}
     * @memberof OrderFulfillment
     */
    sellerId?: any;
    /**
     * 
     * @type {string}
     * @memberof OrderFulfillment
     */
    buyerId?: any;
    /**
     * 
     * @type {SaleType}
     * @memberof OrderFulfillment
     */
    saleType?: any;
    /**
     * 
     * @type {SellerOrderStatus}
     * @memberof OrderFulfillment
     */
    sellerOrderStatus?: any;
    /**
     * 
     * @type {BuyerOrderStatus}
     * @memberof OrderFulfillment
     */
    buyerOrderStatus?: any;
    /**
     * 
     * @type {string}
     * @memberof OrderFulfillment
     */
    buyerTransactionId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof OrderFulfillment
     */
    chargeTransactionId?: any | null;
    /**
     * 
     * @type {Merchant}
     * @memberof OrderFulfillment
     */
    merchant?: any;
}
