/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Merchant } from './merchant';
import { PaymentMethod } from './payment-method';
/**
 * 
 * @export
 * @interface Payment
 */
export interface Payment {
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Payment
     */
    cardToken?: string | null;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof Payment
     */
    type?: PaymentMethod;
    /**
     * 
     * @type {Merchant}
     * @memberof Payment
     */
    provider?: Merchant;
}
