/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PaymentOption
 */
export interface PaymentOption {
    /**
     * 
     * @type {string}
     * @memberof PaymentOption
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentOption
     */
    isDeleted?: any;
    /**
     * 
     * @type {Date}
     * @memberof PaymentOption
     */
    created?: any;
    /**
     * 
     * @type {Date}
     * @memberof PaymentOption
     */
    updated?: any;
    /**
     * 
     * @type {string}
     * @memberof PaymentOption
     */
    userId?: any;
    /**
     * 
     * @type {string}
     * @memberof PaymentOption
     */
    customerId?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOption
     */
    provider?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentOption
     */
    type?: any | null;
}
