/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PayoutBalanceViewModel
 */
export interface PayoutBalanceViewModel {
    /**
     * 
     * @type {number}
     * @memberof PayoutBalanceViewModel
     */
    pendingBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof PayoutBalanceViewModel
     */
    availableBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof PayoutBalanceViewModel
     */
    remainderBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof PayoutBalanceViewModel
     */
    totalBalance?: number;
}
