/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PhysicalAssetAttributes } from './physical-asset-attributes';
import { ProductCondition } from './product-condition';
import { SaleStatus } from './sale-status';
import { SaleType } from './sale-type';
import { UserRole } from './user-role';
/**
 * 
 * @export
 * @interface PhysicalSaleViewModel
 */
export interface PhysicalSaleViewModel {
    /**
     * 
     * @type {string}
     * @memberof PhysicalSaleViewModel
     */
    physicalAssetId?: string;
    /**
     * 
     * @type {string}
     * @memberof PhysicalSaleViewModel
     */
    saleId?: string;
    /**
     * 
     * @type {SaleType}
     * @memberof PhysicalSaleViewModel
     */
    saleType?: SaleType;
    /**
     * 
     * @type {SaleStatus}
     * @memberof PhysicalSaleViewModel
     */
    saleStatus?: SaleStatus;
    /**
     * 
     * @type {number}
     * @memberof PhysicalSaleViewModel
     */
    floorPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof PhysicalSaleViewModel
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof PhysicalSaleViewModel
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof PhysicalSaleViewModel
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PhysicalSaleViewModel
     */
    description?: string | null;
    /**
     * 
     * @type {ProductCondition}
     * @memberof PhysicalSaleViewModel
     */
    condition?: ProductCondition;
    /**
     * 
     * @type {PhysicalAssetAttributes}
     * @memberof PhysicalSaleViewModel
     */
    physicalAssetAttributes?: PhysicalAssetAttributes;
    /**
     * 
     * @type {string}
     * @memberof PhysicalSaleViewModel
     */
    userName?: string | null;
    /**
     * 
     * @type {UserRole}
     * @memberof PhysicalSaleViewModel
     */
    userRole?: UserRole;
    /**
     * 
     * @type {string}
     * @memberof PhysicalSaleViewModel
     */
    profilePicUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PhysicalSaleViewModel
     */
    coverImageUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PhysicalSaleViewModel
     */
    isProfilePicVideo?: boolean;
}
