/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PackageSizeUnit } from './package-size-unit';
import { PackageWeightUnit } from './package-weight-unit';
import { PhysicalAssetAttributes } from './physical-asset-attributes';
import { PhysicalAssetStatus } from './physical-asset-status';
import { PhysicalAssetType } from './physical-asset-type';
import { ProductCondition } from './product-condition';
/**
 * 
 * @export
 * @interface PhysicalAsset
 */
export interface PhysicalAsset {
    /**
     * 
     * @type {string}
     * @memberof PhysicalAsset
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PhysicalAsset
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PhysicalAsset
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PhysicalAsset
     */
    updated?: Date;
    /**
     * 
     * @type {string}
     * @memberof PhysicalAsset
     */
    saleId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PhysicalAsset
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof PhysicalAsset
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PhysicalAsset
     */
    description?: string | null;
    /**
     * 
     * @type {PhysicalAssetStatus}
     * @memberof PhysicalAsset
     */
    physicalAssetStatus?: PhysicalAssetStatus;
    /**
     * 
     * @type {PhysicalAssetType}
     * @memberof PhysicalAsset
     */
    physicalAssetType?: PhysicalAssetType;
    /**
     * 
     * @type {number}
     * @memberof PhysicalAsset
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof PhysicalAsset
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof PhysicalAsset
     */
    length?: number;
    /**
     * 
     * @type {PackageSizeUnit}
     * @memberof PhysicalAsset
     */
    packageSizeUnit?: PackageSizeUnit;
    /**
     * 
     * @type {number}
     * @memberof PhysicalAsset
     */
    weight?: number;
    /**
     * 
     * @type {PackageWeightUnit}
     * @memberof PhysicalAsset
     */
    packageWeightUnit?: PackageWeightUnit;
    /**
     * 
     * @type {ProductCondition}
     * @memberof PhysicalAsset
     */
    productCondition?: ProductCondition;
    /**
     * 
     * @type {string}
     * @memberof PhysicalAsset
     */
    categoryId?: string | null;
    /**
     * 
     * @type {PhysicalAssetAttributes}
     * @memberof PhysicalAsset
     */
    physicalAssetAttributes?: PhysicalAssetAttributes;
}
