/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RoomRequest
 */
export interface RoomRequest {
    /**
     * 
     * @type {string}
     * @memberof RoomRequest
     */
    sessionId?: any;
    /**
     * 
     * @type {string}
     * @memberof RoomRequest
     */
    userId?: any;
    /**
     * 
     * @type {SessionUserRole}
     * @memberof RoomRequest
     */
    role?: any;
    /**
     * 
     * @type {FeedType}
     * @memberof RoomRequest
     */
    feedType?: any;
    /**
     * 
     * @type {VideoService}
     * @memberof RoomRequest
     */
    videoService?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof RoomRequest
     */
    roomAttributes?: any | null;
}
