/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SaleStatus } from './sale-status';
/**
 * 
 * @export
 * @interface SaleStatusResponse
 */
export interface SaleStatusResponse {
    /**
     * 
     * @type {SaleStatus}
     * @memberof SaleStatusResponse
     */
    saleStatus?: SaleStatus;
    /**
     * 
     * @type {string}
     * @memberof SaleStatusResponse
     */
    buyerId?: string | null;
}
