/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderType } from './order-type';
/**
 * 
 * @export
 * @interface SaleOfferResponseModel
 */
export interface SaleOfferResponseModel {
    /**
     * 
     * @type {string}
     * @memberof SaleOfferResponseModel
     */
    userName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SaleOfferResponseModel
     */
    amount?: number;
    /**
     * 
     * @type {OrderType}
     * @memberof SaleOfferResponseModel
     */
    offerType?: OrderType;
}
