/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Livestream } from './livestream';
import { SaleWithAssets } from './sale-with-assets';
/**
 * 
 * @export
 * @interface SaveLivestreamRequest
 */
export interface SaveLivestreamRequest {
    /**
     * 
     * @type {Livestream}
     * @memberof SaveLivestreamRequest
     */
    livestream?: Livestream;
    /**
     * 
     * @type {Array<SaleWithAssets>}
     * @memberof SaveLivestreamRequest
     */
    salesWithAssets?: Array<SaleWithAssets> | null;
}
