/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SellerOrderDTO } from './seller-order-dto';
import { UserAttributes } from './user-attributes';
/**
 * 
 * @export
 * @interface SellerOrdersViewModel
 */
export interface SellerOrdersViewModel {
    /**
     * 
     * @type {string}
     * @memberof SellerOrdersViewModel
     */
    buyerId?: string;
    /**
     * 
     * @type {string}
     * @memberof SellerOrdersViewModel
     */
    buyerName?: string | null;
    /**
     * 
     * @type {UserAttributes}
     * @memberof SellerOrdersViewModel
     */
    buyerAttributes?: UserAttributes;
    /**
     * 
     * @type {Array<SellerOrderDTO>}
     * @memberof SellerOrdersViewModel
     */
    sellerOrders?: Array<SellerOrderDTO> | null;
}
