/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PackageDeliveryStatus } from './package-delivery-status';
import { PackageSizeUnit } from './package-size-unit';
import { PackageWeightUnit } from './package-weight-unit';
/**
 * 
 * @export
 * @interface Shipment
 */
export interface Shipment {
    /**
     * 
     * @type {string}
     * @memberof Shipment
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Shipment
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Shipment
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Shipment
     */
    updated?: Date;
    /**
     * 
     * @type {number}
     * @memberof Shipment
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof Shipment
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof Shipment
     */
    length?: number;
    /**
     * 
     * @type {PackageSizeUnit}
     * @memberof Shipment
     */
    packageSizeUnit?: PackageSizeUnit;
    /**
     * 
     * @type {number}
     * @memberof Shipment
     */
    weight?: number;
    /**
     * 
     * @type {PackageWeightUnit}
     * @memberof Shipment
     */
    packageWeightUnit?: PackageWeightUnit;
    /**
     * 
     * @type {any}
     * @memberof Shipment
     */
    shipmentAttributes?: any | null;
    /**
     * 
     * @type {any}
     * @memberof Shipment
     */
    rateAttributes?: any | null;
    /**
     * 
     * @type {string}
     * @memberof Shipment
     */
    orderId?: string;
    /**
     * 
     * @type {PackageDeliveryStatus}
     * @memberof Shipment
     */
    packageDeliveryStatus?: PackageDeliveryStatus;
}
