/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SocialPost } from './social-post';
/**
 * 
 * @export
 * @interface SocialPostViewModel
 */
export interface SocialPostViewModel {
    /**
     * 
     * @type {SocialPost}
     * @memberof SocialPostViewModel
     */
    socialPost?: SocialPost;
    /**
     * 
     * @type {number}
     * @memberof SocialPostViewModel
     */
    likeCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SocialPostViewModel
     */
    doesCurrentUserLikePost?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SocialPostViewModel
     */
    dislikeCount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SocialPostViewModel
     */
    doesCurrentUserDislikePost?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SocialPostViewModel
     */
    viewCount?: number;
    /**
     * 
     * @type {Array<SocialPost>}
     * @memberof SocialPostViewModel
     */
    comments?: Array<SocialPost> | null;
}
