/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserSale
 */
export interface UserSale {
    /**
     * 
     * @type {string}
     * @memberof UserSale
     */
    buyerUserId?: any;
    /**
     * 
     * @type {string}
     * @memberof UserSale
     */
    buyerUserName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserSale
     */
    nft?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UserSale
     */
    floorPrice?: any;
    /**
     * 
     * @type {number}
     * @memberof UserSale
     */
    soldAmount?: any;
}
