/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PackageDeliveryStatus } from './package-delivery-status';
import { PhysicalAssetAttributes } from './physical-asset-attributes';
/**
 * 
 * @export
 * @interface UserOrder
 */
export interface UserOrder {
    /**
     * 
     * @type {string}
     * @memberof UserOrder
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOrder
     */
    shipmentId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOrder
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOrder
     */
    sellerName?: string | null;
    /**
     * 
     * @type {PhysicalAssetAttributes}
     * @memberof UserOrder
     */
    productAttributes?: PhysicalAssetAttributes;
    /**
     * 
     * @type {PackageDeliveryStatus}
     * @memberof UserOrder
     */
    packageDeliveryStatus?: PackageDeliveryStatus;
    /**
     * 
     * @type {number}
     * @memberof UserOrder
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof UserOrder
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof UserOrder
     */
    trackingUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOrder
     */
    shippingObjectId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserOrder
     */
    created?: Date;
}
