/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserStatistics
 */
export interface UserStatistics {
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    userId?: any;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    name?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    email?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    phoneNumber?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    bio?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserStatistics
     */
    profilePicUrl?: any | null;
    /**
     * 
     * @type {number}
     * @memberof UserStatistics
     */
    nftCount?: any;
}
