/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserCollectibleAttributes } from './user-collectible-attributes';
/**
 * 
 * @export
 * @interface UserCollectible
 */
export interface UserCollectible {
    /**
     * 
     * @type {string}
     * @memberof UserCollectible
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserCollectible
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserCollectible
     */
    created?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserCollectible
     */
    updated?: Date;
    /**
     * 
     * @type {string}
     * @memberof UserCollectible
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCollectible
     */
    collectibleId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCollectible
     */
    collectibleSeriesId?: string;
    /**
     * 
     * @type {UserCollectibleAttributes}
     * @memberof UserCollectible
     */
    userCollectibleAttributes?: UserCollectibleAttributes;
}
