/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
/**
 * 
 * @export
 * @interface UserAttributes
 */
export interface UserAttributes {
    /**
     * 
     * @type {string}
     * @memberof UserAttributes
     */
    referralId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserAttributes
     */
    isAlphaTester?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserAttributes
     */
    isRebreaksEnabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserAttributes
     */
    profilePicUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserAttributes
     */
    isProfilePicVideo?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserAttributes
     */
    coverImageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAttributes
     */
    bio?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAttributes
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAttributes
     */
    twitter?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAttributes
     */
    paypalEmail?: string | null;
    /**
     * 
     * @type {Address}
     * @memberof UserAttributes
     */
    buyerAddress?: Address;
    /**
     * 
     * @type {Address}
     * @memberof UserAttributes
     */
    sellerAddress?: Address;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserAttributes
     */
    expoPushTokens?: Array<string> | null;
}
