/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SaleAssetWithMetadata } from './sale-asset-with-metadata';
/**
 * 
 * @export
 * @interface UserOfferResponse
 */
export interface UserOfferResponse {
    /**
     * 
     * @type {string}
     * @memberof UserOfferResponse
     */
    saleId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOfferResponse
     */
    buyOrderId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOfferResponse
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserOfferResponse
     */
    userName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserOfferResponse
     */
    listingPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof UserOfferResponse
     */
    offerPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof UserOfferResponse
     */
    counterOfferPrice?: number;
    /**
     * 
     * @type {Date}
     * @memberof UserOfferResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {SaleAssetWithMetadata}
     * @memberof UserOfferResponse
     */
    saleAsset?: SaleAssetWithMetadata;
}
