/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiErrorResponse } from '../models';
import { Bid } from '../models';
/**
 * BidApi - axios parameter creator
 * @export
 */
export const BidApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} bidId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidBidIdDelete: async (bidId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'bidId' is not null or undefined
            if (bidId === null || bidId === undefined) {
                throw new RequiredError('bidId','Required parameter bidId was null or undefined when calling apiV1BidBidIdDelete.');
            }
            const localVarPath = `/api/v1/Bid/{bidId}`
                .replace(`{${"bidId"}}`, encodeURIComponent(String(bidId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidIdGet: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiV1BidIdGet.');
            }
            const localVarPath = `/api/v1/Bid/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Bid} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidPost: async (body?: Bid, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Bid`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Bid} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidPut: async (body?: Bid, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Bid`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BidApi - functional programming interface
 * @export
 */
export const BidApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} bidId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BidBidIdDelete(bidId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await BidApiAxiosParamCreator(configuration).apiV1BidBidIdDelete(bidId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BidIdGet(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bid>> {
            const localVarAxiosArgs = await BidApiAxiosParamCreator(configuration).apiV1BidIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {Bid} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BidPost(body?: Bid, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bid>> {
            const localVarAxiosArgs = await BidApiAxiosParamCreator(configuration).apiV1BidPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {Bid} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BidPut(body?: Bid, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Bid>> {
            const localVarAxiosArgs = await BidApiAxiosParamCreator(configuration).apiV1BidPut(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BidApi - factory interface
 * @export
 */
export const BidApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} bidId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidBidIdDelete(bidId: string, options?: any): AxiosPromise<boolean> {
            return BidApiFp(configuration).apiV1BidBidIdDelete(bidId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidIdGet(id: string, options?: any): AxiosPromise<Bid> {
            return BidApiFp(configuration).apiV1BidIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Bid} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidPost(body?: Bid, options?: any): AxiosPromise<Bid> {
            return BidApiFp(configuration).apiV1BidPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Bid} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BidPut(body?: Bid, options?: any): AxiosPromise<Bid> {
            return BidApiFp(configuration).apiV1BidPut(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BidApi - object-oriented interface
 * @export
 * @class BidApi
 * @extends {BaseAPI}
 */
export class BidApi extends BaseAPI {
    /**
     * 
     * @param {string} bidId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BidApi
     */
    public apiV1BidBidIdDelete(bidId: string, options?: any) {
        return BidApiFp(this.configuration).apiV1BidBidIdDelete(bidId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BidApi
     */
    public apiV1BidIdGet(id: string, options?: any) {
        return BidApiFp(this.configuration).apiV1BidIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {Bid} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BidApi
     */
    public apiV1BidPost(body?: Bid, options?: any) {
        return BidApiFp(this.configuration).apiV1BidPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {Bid} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BidApi
     */
    public apiV1BidPut(body?: Bid, options?: any) {
        return BidApiFp(this.configuration).apiV1BidPut(body, options).then((request) => request(this.axios, this.basePath));
    }
}
