/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiErrorResponse } from '../models';
import { BlockChainRequest } from '../models';
import { Blockchain } from '../models';
import { BlockchainAssetMetadata } from '../models';
/**
 * BlockchainApi - axios parameter creator
 * @export
 */
export const BlockchainApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Blockchain} blockchain 
         * @param {string} contractAddress 
         * @param {string} tokenId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet: async (blockchain: Blockchain, contractAddress: string, tokenId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'blockchain' is not null or undefined
            if (blockchain === null || blockchain === undefined) {
                throw new RequiredError('blockchain','Required parameter blockchain was null or undefined when calling apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet.');
            }
            // verify required parameter 'contractAddress' is not null or undefined
            if (contractAddress === null || contractAddress === undefined) {
                throw new RequiredError('contractAddress','Required parameter contractAddress was null or undefined when calling apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet.');
            }
            // verify required parameter 'tokenId' is not null or undefined
            if (tokenId === null || tokenId === undefined) {
                throw new RequiredError('tokenId','Required parameter tokenId was null or undefined when calling apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet.');
            }
            const localVarPath = `/api/v1/Blockchain/getAssetById/{blockchain}/{contractAddress}/{tokenId}`
                .replace(`{${"blockchain"}}`, encodeURIComponent(String(blockchain)))
                .replace(`{${"contractAddress"}}`, encodeURIComponent(String(contractAddress)))
                .replace(`{${"tokenId"}}`, encodeURIComponent(String(tokenId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {BlockChainRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlockchainGetAssetsPost: async (body?: BlockChainRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Blockchain/GetAssets`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1BlockchainGetIPFSMediaPost: async (body?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Blockchain/GetIPFSMedia`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BlockchainApi - functional programming interface
 * @export
 */
export const BlockchainApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Blockchain} blockchain 
         * @param {string} contractAddress 
         * @param {string} tokenId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet(blockchain: Blockchain, contractAddress: string, tokenId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<BlockchainAssetMetadata>>> {
            const localVarAxiosArgs = await BlockchainApiAxiosParamCreator(configuration).apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet(blockchain, contractAddress, tokenId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {BlockChainRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlockchainGetAssetsPost(body?: BlockChainRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<BlockchainAssetMetadata>>>> {
            const localVarAxiosArgs = await BlockchainApiAxiosParamCreator(configuration).apiV1BlockchainGetAssetsPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlockchainGetIPFSMediaPost(body?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await BlockchainApiAxiosParamCreator(configuration).apiV1BlockchainGetIPFSMediaPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * BlockchainApi - factory interface
 * @export
 */
export const BlockchainApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {Blockchain} blockchain 
         * @param {string} contractAddress 
         * @param {string} tokenId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet(blockchain: Blockchain, contractAddress: string, tokenId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<BlockchainAssetMetadata>> {
            return BlockchainApiFp(configuration).apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet(blockchain, contractAddress, tokenId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BlockChainRequest} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlockchainGetAssetsPost(body?: BlockChainRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<BlockchainAssetMetadata>>> {
            return BlockchainApiFp(configuration).apiV1BlockchainGetAssetsPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1BlockchainGetIPFSMediaPost(body?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return BlockchainApiFp(configuration).apiV1BlockchainGetIPFSMediaPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BlockchainApi - object-oriented interface
 * @export
 * @class BlockchainApi
 * @extends {BaseAPI}
 */
export class BlockchainApi extends BaseAPI {
    /**
     * 
     * @param {Blockchain} blockchain 
     * @param {string} contractAddress 
     * @param {string} tokenId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlockchainApi
     */
    public async apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet(blockchain: Blockchain, contractAddress: string, tokenId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<BlockchainAssetMetadata>> {
        return BlockchainApiFp(this.configuration).apiV1BlockchainGetAssetByIdBlockchainContractAddressTokenIdGet(blockchain, contractAddress, tokenId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {BlockChainRequest} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlockchainApi
     */
    public async apiV1BlockchainGetAssetsPost(body?: BlockChainRequest, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<BlockchainAssetMetadata>>> {
        return BlockchainApiFp(this.configuration).apiV1BlockchainGetAssetsPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlockchainApi
     */
    public async apiV1BlockchainGetIPFSMediaPost(body?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return BlockchainApiFp(this.configuration).apiV1BlockchainGetIPFSMediaPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
