/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiErrorResponse } from '../models';
import { User } from '../models';
/**
 * FollowerApi - axios parameter creator
 * @export
 */
export const FollowerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1FollowerCheckIfFollowingHostIdFollowerIdGet: async (hostId: string, followerId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'hostId' is not null or undefined
            if (hostId === null || hostId === undefined) {
                throw new RequiredError('hostId','Required parameter hostId was null or undefined when calling apiV1FollowerCheckIfFollowingHostIdFollowerIdGet.');
            }
            // verify required parameter 'followerId' is not null or undefined
            if (followerId === null || followerId === undefined) {
                throw new RequiredError('followerId','Required parameter followerId was null or undefined when calling apiV1FollowerCheckIfFollowingHostIdFollowerIdGet.');
            }
            const localVarPath = `/api/v1/Follower/checkIfFollowing/{hostId}/{followerId}`
                .replace(`{${"hostId"}}`, encodeURIComponent(String(hostId)))
                .replace(`{${"followerId"}}`, encodeURIComponent(String(followerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1FollowerFollowHostIdFollowerIdPost: async (hostId: string, followerId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'hostId' is not null or undefined
            if (hostId === null || hostId === undefined) {
                throw new RequiredError('hostId','Required parameter hostId was null or undefined when calling apiV1FollowerFollowHostIdFollowerIdPost.');
            }
            // verify required parameter 'followerId' is not null or undefined
            if (followerId === null || followerId === undefined) {
                throw new RequiredError('followerId','Required parameter followerId was null or undefined when calling apiV1FollowerFollowHostIdFollowerIdPost.');
            }
            const localVarPath = `/api/v1/Follower/follow/{hostId}/{followerId}`
                .replace(`{${"hostId"}}`, encodeURIComponent(String(hostId)))
                .replace(`{${"followerId"}}`, encodeURIComponent(String(followerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1FollowerGetAllFollowersGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/Follower/getAllFollowers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1FollowerUnfollowHostIdFollowerIdPost: async (hostId: string, followerId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'hostId' is not null or undefined
            if (hostId === null || hostId === undefined) {
                throw new RequiredError('hostId','Required parameter hostId was null or undefined when calling apiV1FollowerUnfollowHostIdFollowerIdPost.');
            }
            // verify required parameter 'followerId' is not null or undefined
            if (followerId === null || followerId === undefined) {
                throw new RequiredError('followerId','Required parameter followerId was null or undefined when calling apiV1FollowerUnfollowHostIdFollowerIdPost.');
            }
            const localVarPath = `/api/v1/Follower/unfollow/{hostId}/{followerId}`
                .replace(`{${"hostId"}}`, encodeURIComponent(String(hostId)))
                .replace(`{${"followerId"}}`, encodeURIComponent(String(followerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FollowerApi - functional programming interface
 * @export
 */
export const FollowerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1FollowerCheckIfFollowingHostIdFollowerIdGet(hostId: string, followerId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await FollowerApiAxiosParamCreator(configuration).apiV1FollowerCheckIfFollowingHostIdFollowerIdGet(hostId, followerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1FollowerFollowHostIdFollowerIdPost(hostId: string, followerId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await FollowerApiAxiosParamCreator(configuration).apiV1FollowerFollowHostIdFollowerIdPost(hostId, followerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1FollowerGetAllFollowersGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await FollowerApiAxiosParamCreator(configuration).apiV1FollowerGetAllFollowersGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1FollowerUnfollowHostIdFollowerIdPost(hostId: string, followerId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await FollowerApiAxiosParamCreator(configuration).apiV1FollowerUnfollowHostIdFollowerIdPost(hostId, followerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * FollowerApi - factory interface
 * @export
 */
export const FollowerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1FollowerCheckIfFollowingHostIdFollowerIdGet(hostId: string, followerId: string, options?: any): AxiosPromise<boolean> {
            return FollowerApiFp(configuration).apiV1FollowerCheckIfFollowingHostIdFollowerIdGet(hostId, followerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1FollowerFollowHostIdFollowerIdPost(hostId: string, followerId: string, options?: any): AxiosPromise<boolean> {
            return FollowerApiFp(configuration).apiV1FollowerFollowHostIdFollowerIdPost(hostId, followerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1FollowerGetAllFollowersGet(options?: any): AxiosPromise<Array<User>> {
            return FollowerApiFp(configuration).apiV1FollowerGetAllFollowersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} hostId 
         * @param {string} followerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1FollowerUnfollowHostIdFollowerIdPost(hostId: string, followerId: string, options?: any): AxiosPromise<boolean> {
            return FollowerApiFp(configuration).apiV1FollowerUnfollowHostIdFollowerIdPost(hostId, followerId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FollowerApi - object-oriented interface
 * @export
 * @class FollowerApi
 * @extends {BaseAPI}
 */
export class FollowerApi extends BaseAPI {
    /**
     * 
     * @param {string} hostId 
     * @param {string} followerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FollowerApi
     */
    public apiV1FollowerCheckIfFollowingHostIdFollowerIdGet(hostId: string, followerId: string, options?: any) {
        return FollowerApiFp(this.configuration).apiV1FollowerCheckIfFollowingHostIdFollowerIdGet(hostId, followerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} hostId 
     * @param {string} followerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FollowerApi
     */
    public apiV1FollowerFollowHostIdFollowerIdPost(hostId: string, followerId: string, options?: any) {
        return FollowerApiFp(this.configuration).apiV1FollowerFollowHostIdFollowerIdPost(hostId, followerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FollowerApi
     */
    public apiV1FollowerGetAllFollowersGet(options?: any) {
        return FollowerApiFp(this.configuration).apiV1FollowerGetAllFollowersGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} hostId 
     * @param {string} followerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FollowerApi
     */
    public apiV1FollowerUnfollowHostIdFollowerIdPost(hostId: string, followerId: string, options?: any) {
        return FollowerApiFp(this.configuration).apiV1FollowerUnfollowHostIdFollowerIdPost(hostId, followerId, options).then((request) => request(this.axios, this.basePath));
    }
}
