/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiErrorResponse } from '../models';
import { LivestreamAsset } from '../models';
/**
 * LivestreamAssetApi - axios parameter creator
 * @export
 */
export const LivestreamAssetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Array&lt;LivestreamAsset&gt;} [body] 
         * @param {string} [livestreamId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1LivestreamAssetPost: async (body?: Array<LivestreamAsset>, livestreamId?: string, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/LivestreamAsset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (livestreamId !== undefined) {
                localVarQueryParameter['livestreamId'] = livestreamId;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LivestreamAssetApi - functional programming interface
 * @export
 */
export const LivestreamAssetApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Array&lt;LivestreamAsset&gt;} [body] 
         * @param {string} [livestreamId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1LivestreamAssetPost(body?: Array<LivestreamAsset>, livestreamId?: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await LivestreamAssetApiAxiosParamCreator(configuration).apiV1LivestreamAssetPost(body, livestreamId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * LivestreamAssetApi - factory interface
 * @export
 */
export const LivestreamAssetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {Array&lt;LivestreamAsset&gt;} [body] 
         * @param {string} [livestreamId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1LivestreamAssetPost(body?: Array<LivestreamAsset>, livestreamId?: string, options?: any): AxiosPromise<boolean> {
            return LivestreamAssetApiFp(configuration).apiV1LivestreamAssetPost(body, livestreamId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LivestreamAssetApi - object-oriented interface
 * @export
 * @class LivestreamAssetApi
 * @extends {BaseAPI}
 */
export class LivestreamAssetApi extends BaseAPI {
    /**
     * 
     * @param {Array&lt;LivestreamAsset&gt;} [body] 
     * @param {string} [livestreamId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LivestreamAssetApi
     */
    public apiV1LivestreamAssetPost(body?: Array<LivestreamAsset>, livestreamId?: string, options?: any) {
        return LivestreamAssetApiFp(this.configuration).apiV1LivestreamAssetPost(body, livestreamId, options).then((request) => request(this.axios, this.basePath));
    }
}
