/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ApiErrorResponse } from '../models';
/**
 * NotificationApi - axios parameter creator
 * @export
 */
export const NotificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} toUserId 
         * @param {string} fromUserName 
         * @param {string} fromUserId 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1NotificationDmFromUserNameFromUserIdToUserIdPost: async (toUserId: string, fromUserName: string, fromUserId: string, body?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'toUserId' is not null or undefined
            if (toUserId === null || toUserId === undefined) {
                throw new RequiredError('toUserId','Required parameter toUserId was null or undefined when calling apiV1NotificationDmFromUserNameFromUserIdToUserIdPost.');
            }
            // verify required parameter 'fromUserName' is not null or undefined
            if (fromUserName === null || fromUserName === undefined) {
                throw new RequiredError('fromUserName','Required parameter fromUserName was null or undefined when calling apiV1NotificationDmFromUserNameFromUserIdToUserIdPost.');
            }
            // verify required parameter 'fromUserId' is not null or undefined
            if (fromUserId === null || fromUserId === undefined) {
                throw new RequiredError('fromUserId','Required parameter fromUserId was null or undefined when calling apiV1NotificationDmFromUserNameFromUserIdToUserIdPost.');
            }
            const localVarPath = `/api/v1/Notification/dm/{fromUserName}/{fromUserId}/{toUserId}`
                .replace(`{${"toUserId"}}`, encodeURIComponent(String(toUserId)))
                .replace(`{${"fromUserName"}}`, encodeURIComponent(String(fromUserName)))
                .replace(`{${"fromUserId"}}`, encodeURIComponent(String(fromUserId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} livestreamId 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1NotificationTagLivestreamIdPost: async (livestreamId: string, body?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'livestreamId' is not null or undefined
            if (livestreamId === null || livestreamId === undefined) {
                throw new RequiredError('livestreamId','Required parameter livestreamId was null or undefined when calling apiV1NotificationTagLivestreamIdPost.');
            }
            const localVarPath = `/api/v1/Notification/tag/{livestreamId}`
                .replace(`{${"livestreamId"}}`, encodeURIComponent(String(livestreamId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationApi - functional programming interface
 * @export
 */
export const NotificationApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} toUserId 
         * @param {string} fromUserName 
         * @param {string} fromUserId 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1NotificationDmFromUserNameFromUserIdToUserIdPost(toUserId: string, fromUserName: string, fromUserId: string, body?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await NotificationApiAxiosParamCreator(configuration).apiV1NotificationDmFromUserNameFromUserIdToUserIdPost(toUserId, fromUserName, fromUserId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} livestreamId 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1NotificationTagLivestreamIdPost(livestreamId: string, body?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await NotificationApiAxiosParamCreator(configuration).apiV1NotificationTagLivestreamIdPost(livestreamId, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * NotificationApi - factory interface
 * @export
 */
export const NotificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} toUserId 
         * @param {string} fromUserName 
         * @param {string} fromUserId 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1NotificationDmFromUserNameFromUserIdToUserIdPost(toUserId: string, fromUserName: string, fromUserId: string, body?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return NotificationApiFp(configuration).apiV1NotificationDmFromUserNameFromUserIdToUserIdPost(toUserId, fromUserName, fromUserId, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} livestreamId 
         * @param {string} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1NotificationTagLivestreamIdPost(livestreamId: string, body?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return NotificationApiFp(configuration).apiV1NotificationTagLivestreamIdPost(livestreamId, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationApi - object-oriented interface
 * @export
 * @class NotificationApi
 * @extends {BaseAPI}
 */
export class NotificationApi extends BaseAPI {
    /**
     * 
     * @param {string} toUserId 
     * @param {string} fromUserName 
     * @param {string} fromUserId 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationApi
     */
    public async apiV1NotificationDmFromUserNameFromUserIdToUserIdPost(toUserId: string, fromUserName: string, fromUserId: string, body?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return NotificationApiFp(this.configuration).apiV1NotificationDmFromUserNameFromUserIdToUserIdPost(toUserId, fromUserName, fromUserId, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} livestreamId 
     * @param {string} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationApi
     */
    public async apiV1NotificationTagLivestreamIdPost(livestreamId: string, body?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return NotificationApiFp(this.configuration).apiV1NotificationTagLivestreamIdPost(livestreamId, body, options).then((request) => request(this.axios, this.basePath));
    }
}
