/* tslint:disable */
/* eslint-disable */
/**
 * Conifer.NFT.API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * ShipmentApi - axios parameter creator
 * @export
 */
export const ShipmentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [saleId] 
         * @param {number} [quantity] 
         * @param {string} [sellerId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiShipmentGetShipmentRatePost: async (saleId?: string, quantity?: number, sellerId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Shipment/GetShipmentRate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (saleId !== undefined) {
                localVarQueryParameter['saleId'] = saleId;
            }

            if (quantity !== undefined) {
                localVarQueryParameter['quantity'] = quantity;
            }

            if (sellerId !== undefined) {
                localVarQueryParameter['sellerId'] = sellerId;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ShipmentApi - functional programming interface
 * @export
 */
export const ShipmentApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [saleId] 
         * @param {number} [quantity] 
         * @param {string} [sellerId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiShipmentGetShipmentRatePost(saleId?: string, quantity?: number, sellerId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<number>>> {
            const localVarAxiosArgs = await ShipmentApiAxiosParamCreator(configuration).apiShipmentGetShipmentRatePost(saleId, quantity, sellerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ShipmentApi - factory interface
 * @export
 */
export const ShipmentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} [saleId] 
         * @param {number} [quantity] 
         * @param {string} [sellerId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiShipmentGetShipmentRatePost(saleId?: string, quantity?: number, sellerId?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<number>> {
            return ShipmentApiFp(configuration).apiShipmentGetShipmentRatePost(saleId, quantity, sellerId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ShipmentApi - object-oriented interface
 * @export
 * @class ShipmentApi
 * @extends {BaseAPI}
 */
export class ShipmentApi extends BaseAPI {
    /**
     * 
     * @param {string} [saleId] 
     * @param {number} [quantity] 
     * @param {string} [sellerId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ShipmentApi
     */
    public async apiShipmentGetShipmentRatePost(saleId?: string, quantity?: number, sellerId?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<number>> {
        return ShipmentApiFp(this.configuration).apiShipmentGetShipmentRatePost(saleId, quantity, sellerId, options).then((request) => request(this.axios, this.basePath));
    }
}
